name: packagist_mvc
description: 基础MVC框架封装
version: 1.1.6
homepage: https://github.com/flutter-packagist/mvc

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
